/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RestaurantManagementSystem;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       // System.out.println(new App().getGreeting());
       ManagementSystem management = new ManagementSystem();
       MainForm mainForm = new MainForm(management);
       Controller controller = new Controller(mainForm);
       
       controller.showForm();
    
    }
}
