package lab15;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author jannalomibao
 */
public class MainForm extends javax.swing.JFrame {
    private ResourceBundle bundle;
    private ResourceBundle bundleFR;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        
        bundle = ResourceBundle.getBundle("FormLanguage");
        bundleFR = ResourceBundle.getBundle("FormLanguage", Locale.FRANCE);
        englishRadioButton.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bookCategoryComboBox = new javax.swing.JComboBox<>();
        bookIDLabel = new javax.swing.JLabel();
        borrowButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        statusDisplayLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        englishRadioButton = new javax.swing.JRadioButton();
        frenchRadioButton = new javax.swing.JRadioButton();
        bookListLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookListTextArea = new javax.swing.JTextArea();
        bookIDTextField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        bookTitleLabel = new javax.swing.JLabel();
        statusBookLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Form");

        titleLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        titleLabel.setLabelFor(this);
        titleLabel.setText("XYZ Library");
        titleLabel.setName(""); // NOI18N

        bookCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fiction", "Academic", "Biography" }));
        bookCategoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookCategoryComboBoxActionPerformed(evt);
            }
        });

        bookIDLabel.setLabelFor(bookIDTextField);
        bookIDLabel.setText("Book ID.");

        borrowButton.setText("Borrow");
        borrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowButtonActionPerformed(evt);
            }
        });

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        statusDisplayLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        statusLabel.setLabelFor(statusDisplayLabel);
        statusLabel.setText("Status:");

        englishRadioButton.setText("English");
        englishRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishRadioButtonActionPerformed(evt);
            }
        });

        frenchRadioButton.setText("French");
        frenchRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frenchRadioButtonActionPerformed(evt);
            }
        });

        bookListLabel.setLabelFor(bookCategoryComboBox);
        bookListLabel.setText("Categories:");

        bookListTextArea.setColumns(20);
        bookListTextArea.setRows(5);
        jScrollPane1.setViewportView(bookListTextArea);

        idLabel.setText("ID");

        bookTitleLabel.setText("Title");

        statusBookLabel.setText("Status");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(titleLabel)
                        .addGap(18, 108, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(borrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(statusLabel)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(englishRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(frenchRadioButton)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(statusDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bookIDLabel)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(bookIDTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bookCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchButton))
                    .addComponent(bookListLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(idLabel)
                            .addGap(47, 47, 47)
                            .addComponent(bookTitleLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statusBookLabel))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(bookListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(bookTitleLabel)
                    .addComponent(statusBookLabel))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titleLabel)
                .addGap(35, 35, 35)
                .addComponent(bookIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(statusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(englishRadioButton)
                    .addComponent(frenchRadioButton))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frenchRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frenchRadioButtonActionPerformed
        // TODO add your handling code here:
//        
        titleLabel.setText(bundleFR.getString("TitleLabel"));
        bookIDLabel.setText(bundleFR.getString("BookIDLabel"));
        borrowButton.setText(bundleFR.getString("BorrowButton"));
        returnButton.setText(bundleFR.getString("ReturnButton"));
        statusLabel.setText(bundleFR.getString("StatusLabel"));
        bookListLabel.setText(bundleFR.getString("BookListLabel"));
        searchButton.setText(bundleFR.getString("SearchButton"));
        idLabel.setText(bundleFR.getString("IDLabel"));
        bookTitleLabel.setText(bundleFR.getString("BookTitleLabel"));
        statusBookLabel.setText(bundleFR.getString("StatusBooklabel"));
        bookCategoryComboBox.removeAllItems();

        // Add new items with the translated text from the French resource bundle
        bookCategoryComboBox.addItem(bundleFR.getString("Fiction"));
        bookCategoryComboBox.addItem(bundleFR.getString("Academic"));
        bookCategoryComboBox.addItem(bundleFR.getString("Biography"));
        englishRadioButton.setSelected(false);
                
    }//GEN-LAST:event_frenchRadioButtonActionPerformed

    private void borrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowButtonActionPerformed
        // when borrow button is clicked, we update the hashmap of the book selected from true to false
        int idEntered = Integer.parseInt(bookIDTextField.getText());
        boolean borrowStatus = Controller.getInstance().getLibrary().borrowBook(idEntered);
        
        if (borrowStatus) {
            if (frenchRadioButton.isSelected()) {
                statusDisplayLabel.setText(bundleFR.getString("BookBorrowedSuccess"));
            } else {
                statusDisplayLabel.setText(bundle.getString("BookBorrowedSuccess"));
            }
        } else {
            if (frenchRadioButton.isSelected()) {
                statusDisplayLabel.setText(bundleFR.getString("BookBorrowedFail"));
            } else {
                statusDisplayLabel.setText(bundle.getString("BookBorrowedFail"));
            }
        }
        //bookCategoryComboBoxActionPerformed(evt);

    }//GEN-LAST:event_borrowButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
        int idEntered = Integer.parseInt(bookIDTextField.getText());
        boolean returnStatus = Controller.getInstance().getLibrary().returnBook(idEntered);
        
        if (returnStatus) {
            if (frenchRadioButton.isSelected()) {
                statusDisplayLabel.setText(bundleFR.getString("BookReturnedSuccess"));
            } else {
                statusDisplayLabel.setText(bundle.getString("BookReturnedSuccess"));
            }
        } else {
            if (frenchRadioButton.isSelected()) {
                statusDisplayLabel.setText(bundleFR.getString("BookReturnedFail"));
            } else {
                statusDisplayLabel.setText(bundle.getString("BookReturnedFail"));
            }
    
        }
        
         //bookCategoryComboBoxActionPerformed(evt);
    }//GEN-LAST:event_returnButtonActionPerformed

    private void bookCategoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookCategoryComboBoxActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_bookCategoryComboBoxActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        HashMap <String, String> map = new HashMap<>();
        map.put("Littérature","Fiction");
        map.put("Académique", "Academic");
        map.put("Biographie", "Biography");
        
        String selected = bookCategoryComboBox.getSelectedItem().toString();
        
        if(frenchRadioButton.isSelected()){
            selected = map.get(selected);
        }
        
        bookListTextArea.setText("");
        // Get the list of books for the selected category
         List<BookAbstract> books = Controller.getInstance().getLibrary().getBooksByCategory(selected);
    
    
        // Display the list of books in the text area
        for (BookAbstract book : books) {
            boolean isAvail = Controller.getInstance().getLibrary().isAvailable(book.getId());
            bookListTextArea.append("ID: " + book.getId() + "\t Title: " + book.getTitle() + "\t Status: " + (isAvail ? "Available" : "Borrowed") + "\n");
        }
      

    }//GEN-LAST:event_searchButtonActionPerformed

    private void englishRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishRadioButtonActionPerformed
        // TODO add your handling code here:
        titleLabel.setText(bundleFR.getString("TitleLabel"));
        bookIDLabel.setText(bundleFR.getString("BookIDLabel"));
        borrowButton.setText(bundleFR.getString("BorrowButton"));
        returnButton.setText(bundleFR.getString("ReturnButton"));
        statusLabel.setText(bundleFR.getString("StatusLabel"));
        bookListLabel.setText(bundleFR.getString("BookListLabel"));
        //bookCategoryComboBox.setTe
        searchButton.setText(bundleFR.getString("SearchButton"));
        idLabel.setText(bundleFR.getString("IDLabel"));
        bookTitleLabel.setText(bundleFR.getString("BookTitleLabel"));
        statusBookLabel.setText(bundleFR.getString("StatusBooklabel"));
        frenchRadioButton.setSelected(false);
    }//GEN-LAST:event_englishRadioButtonActionPerformed
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bookCategoryComboBox;
    private javax.swing.JLabel bookIDLabel;
    private javax.swing.JTextField bookIDTextField;
    private javax.swing.JLabel bookListLabel;
    private javax.swing.JTextArea bookListTextArea;
    private javax.swing.JLabel bookTitleLabel;
    private javax.swing.JButton borrowButton;
    private javax.swing.JRadioButton englishRadioButton;
    private javax.swing.JRadioButton frenchRadioButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel statusBookLabel;
    private javax.swing.JLabel statusDisplayLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
