/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab16;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author jannalomibao
 */
public class MainForm extends javax.swing.JFrame {
    private ResourceBundle bundle;
    private ResourceBundle bundleFR;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        bundle = ResourceBundle.getBundle("FormLanguage");
        bundleFR = ResourceBundle.getBundle("FormLanguage", Locale.FRANCE);
        englishRadioButton.setSelected(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        patientNumberLabel = new javax.swing.JLabel();
        patientnumberTextField = new javax.swing.JTextField();
        wardServiceLabel = new javax.swing.JLabel();
        diagnosticServicesLabel = new javax.swing.JLabel();
        bloodTestCheckBox = new javax.swing.JCheckBox();
        radiologyServiceLabel = new javax.swing.JLabel();
        audiometryCheckBox = new javax.swing.JCheckBox();
        auscultationCheckBox = new javax.swing.JCheckBox();
        notifyDoctors = new javax.swing.JCheckBox();
        doneButton = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        patientNumberTwoLabel = new javax.swing.JLabel();
        patientNumberSummaryTextFiled = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PatientSummaryTextArea = new javax.swing.JTextArea();
        englishRadioButton = new javax.swing.JRadioButton();
        frenchRadioButton = new javax.swing.JRadioButton();
        wardComboBox = new javax.swing.JComboBox<>();
        ctScanCheckBox = new javax.swing.JCheckBox();
        xrayCheckBox = new javax.swing.JCheckBox();
        mriCheckBox = new javax.swing.JCheckBox();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setText("Inpatient Management System Service");

        patientNumberLabel.setText("Patient Number:");

        patientnumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientnumberTextFieldActionPerformed(evt);
            }
        });

        wardServiceLabel.setText("Ward:");

        diagnosticServicesLabel.setText("Diagnostic Procedures:");

        bloodTestCheckBox.setText("Blood test");
        bloodTestCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodTestCheckBoxActionPerformed(evt);
            }
        });

        radiologyServiceLabel.setText("Radiology Services:");

        audiometryCheckBox.setText("Audiometry");
        audiometryCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audiometryCheckBoxActionPerformed(evt);
            }
        });

        auscultationCheckBox.setText("Auscultation");

        notifyDoctors.setText("Notify the patient's doctors");

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        separator.setForeground(new java.awt.Color(153, 204, 255));
        separator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        patientNumberTwoLabel.setText("Patient Number:");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        PatientSummaryTextArea.setColumns(20);
        PatientSummaryTextArea.setRows(5);
        jScrollPane1.setViewportView(PatientSummaryTextArea);

        englishRadioButton.setText("English");
        englishRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishRadioButtonActionPerformed(evt);
            }
        });

        frenchRadioButton.setText("French");
        frenchRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frenchRadioButtonActionPerformed(evt);
            }
        });

        wardComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ICU", "Admissions ward", "Surgery" }));

        ctScanCheckBox.setText("CT Scan");

        xrayCheckBox.setText("X-ray");

        mriCheckBox.setText("MRI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(140, 140, 140)
                                        .addComponent(titleLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(diagnosticServicesLabel)
                                            .addComponent(bloodTestCheckBox)
                                            .addComponent(audiometryCheckBox)
                                            .addComponent(auscultationCheckBox))
                                        .addGap(139, 139, 139)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radiologyServiceLabel)
                                            .addComponent(ctScanCheckBox)
                                            .addComponent(xrayCheckBox)
                                            .addComponent(mriCheckBox)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(patientNumberLabel)
                                            .addComponent(patientnumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(wardServiceLabel)
                                            .addComponent(wardComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(notifyDoctors)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(englishRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(frenchRadioButton)
                                .addGap(32, 32, 32))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientNumberTwoLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(patientNumberSummaryTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(searchButton))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(patientNumberTwoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNumberSummaryTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titleLabel)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNumberLabel)
                    .addComponent(wardServiceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientnumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wardComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diagnosticServicesLabel)
                    .addComponent(radiologyServiceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodTestCheckBox)
                    .addComponent(ctScanCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(audiometryCheckBox)
                    .addComponent(xrayCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(auscultationCheckBox)
                    .addComponent(mriCheckBox))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(englishRadioButton)
                            .addComponent(frenchRadioButton))
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(notifyDoctors)
                        .addGap(35, 35, 35)
                        .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientnumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientnumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientnumberTextFieldActionPerformed

    private void bloodTestCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodTestCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodTestCheckBoxActionPerformed

    private void audiometryCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audiometryCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_audiometryCheckBoxActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // TODO add your handling code here:
        HashMap<String,InpatientService> map = new HashMap<>();
        map.put("ICU", new ICUWard());
        map.put("Admissions ward", new AdmissionWard());
        map.put("Surgery",new SurgeryWard());
 
        int patientId = Integer.parseInt(patientnumberTextField.getText());
        
        Patient patient = Controller.getInstance().getRecords().getPatient(patientId);
  
        //ward
        String selected = wardComboBox.getSelectedItem().toString();
        InpatientService ward = map.get(selected);
        
        //diagnostic procedures
        if(bloodTestCheckBox.isSelected()){
            patient.addHistory(new BloodTestDecorator(ward));
        }
        if(audiometryCheckBox.isSelected()){
            patient.addHistory(new AudiometryDecorator(ward));
        }
        if(auscultationCheckBox.isSelected()){
            patient.addHistory(new AuscultationServiceDecorator(ward));
        }
        
        //radoilogyServices
        if(ctScanCheckBox.isSelected()){
            patient.addHistory(new CTScanServiceDecorator(ward));
        }
        if(xrayCheckBox.isSelected()){
            patient.addHistory(new XrayServiceDecorator(ward));
        }
        if(mriCheckBox.isSelected()){
            patient.addHistory(new MRIServiceDecorator(ward));
        }
        
        
        //doctor notification
        if(notifyDoctors.isSelected()){
           Controller.getInstance().getRecords().notifyDoctor(patientId);
        }

        clearCheckedBox();
        
        
    }//GEN-LAST:event_doneButtonActionPerformed
    private void clearCheckedBox(){
  
        bloodTestCheckBox.setSelected(false);
        audiometryCheckBox.setSelected(false);
        auscultationCheckBox.setSelected(false);
        ctScanCheckBox.setSelected(false);
        xrayCheckBox.setSelected(false);
        mriCheckBox.setSelected(false);
        patientnumberTextField.setText("");
        notifyDoctors.setSelected(false);
        
    }
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        PatientSummaryTextArea.setText("");
        int searchPatientID = Integer.parseInt(patientNumberSummaryTextFiled.getText());
        
        Patient patient = Controller.getInstance().getRecords().getPatient(searchPatientID);
        
        if(patient != null) {
        // Check if the patient has any history
            if(patient.getHistory().isEmpty()){
                // Display message for empty record
                if (englishRadioButton.isSelected()) {
                    PatientSummaryTextArea.setText(bundle.getString("emptyRecord"));
                } else {
                    PatientSummaryTextArea.setText(bundleFR.getString("emptyRecord"));
                }
                
            } else {
                // Display the patient's history
                PatientSummaryTextArea.setText(patient.getHistoryAsString());
            }
        } else {
        // Display message for patient not found
            if (englishRadioButton.isSelected()) {
                PatientSummaryTextArea.setText(bundle.getString("patientNotFound"));
            } else {
               PatientSummaryTextArea.setText(bundleFR.getString("patientNotFound"));
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void englishRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishRadioButtonActionPerformed
        // TODO add your handling code here:
        frenchRadioButton.setSelected(false);
        audiometryCheckBox.setText(bundle.getString("audiometryCheckBox"));
        auscultationCheckBox.setText(bundle.getString("auscultationCheckBox"));
        bloodTestCheckBox.setText(bundle.getString("bloodTestCheckBox"));
        ctScanCheckBox.setText(bundle.getString("ctScanCheckBox"));
        diagnosticServicesLabel.setText(bundle.getString("diagnosticServicesLabel"));
        doneButton.setText(bundle.getString("doneButton"));
        mriCheckBox.setText(bundle.getString("mriCheckBox"));
        notifyDoctors.setText(bundle.getString("notifyDoctors"));
        patientNumberLabel.setText(bundle.getString("patientNumberLabel"));
        patientNumberTwoLabel.setText(bundle.getString("patientNumberTwoLabel"));
        radiologyServiceLabel.setText(bundle.getString("radiologyServiceLabel"));
        searchButton.setText(bundle.getString("searchButton"));
        titleLabel.setText(bundle.getString("titleLabel"));
        wardServiceLabel.setText(bundle.getString("wardServiceLabel"));
        xrayCheckBox.setText(bundle.getString("xrayCheckBox"));

    }//GEN-LAST:event_englishRadioButtonActionPerformed

    private void frenchRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frenchRadioButtonActionPerformed
        // TODO add your handling code here:
        englishRadioButton.setSelected(false);
        audiometryCheckBox.setText(bundleFR.getString("audiometryCheckBox"));
        auscultationCheckBox.setText(bundleFR.getString("auscultationCheckBox"));
        bloodTestCheckBox.setText(bundleFR.getString("bloodTestCheckBox"));
        ctScanCheckBox.setText(bundleFR.getString("ctScanCheckBox"));
        diagnosticServicesLabel.setText(bundleFR.getString("diagnosticServicesLabel"));
        doneButton.setText(bundleFR.getString("doneButton"));
        mriCheckBox.setText(bundleFR.getString("mriCheckBox"));
        notifyDoctors.setText(bundleFR.getString("notifyDoctors"));
        patientNumberLabel.setText(bundleFR.getString("patientNumberLabel"));
        patientNumberTwoLabel.setText(bundleFR.getString("patientNumberTwoLabel"));
        radiologyServiceLabel.setText(bundleFR.getString("radiologyServiceLabel"));
        searchButton.setText(bundleFR.getString("searchButton"));
        titleLabel.setText(bundleFR.getString("titleLabel"));
        wardServiceLabel.setText(bundleFR.getString("wardServiceLabel"));
        xrayCheckBox.setText(bundleFR.getString("xrayCheckBox"));
    }//GEN-LAST:event_frenchRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea PatientSummaryTextArea;
    private javax.swing.JCheckBox audiometryCheckBox;
    private javax.swing.JCheckBox auscultationCheckBox;
    private javax.swing.JCheckBox bloodTestCheckBox;
    private javax.swing.JCheckBox ctScanCheckBox;
    private javax.swing.JLabel diagnosticServicesLabel;
    private javax.swing.JButton doneButton;
    private javax.swing.JRadioButton englishRadioButton;
    private javax.swing.JRadioButton frenchRadioButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox mriCheckBox;
    private javax.swing.JCheckBox notifyDoctors;
    private javax.swing.JLabel patientNumberLabel;
    private javax.swing.JTextField patientNumberSummaryTextFiled;
    private javax.swing.JLabel patientNumberTwoLabel;
    private javax.swing.JTextField patientnumberTextField;
    private javax.swing.JLabel radiologyServiceLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JSeparator separator;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JComboBox<String> wardComboBox;
    private javax.swing.JLabel wardServiceLabel;
    private javax.swing.JCheckBox xrayCheckBox;
    // End of variables declaration//GEN-END:variables
}
